---
# Docker Compose Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/
# Using Docker Compose for Dev Containers: https://containers.dev/guide/dockerfile#docker-compose-dockerfile

# Networks top-level element reference: https://docs.docker.com/compose/compose-file/06-networks/
networks:
  backend:
  frontend:

# Service top-level element reference: https://docs.docker.com/compose/compose-file/05-services/
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    environment:
      # Enable Docker BuildKit https://docs.docker.com/build/buildkit/
      DOCKER_BUILDKIT: '1'
      DOCKER_REGISTRY_URL: ''    # Required for Maven build
    volumes:
      - ../..:/workspaces:cached    # mounts the workspace folder from the local source tree into the Dev Container.
    command: sleep infinity
    # Red Hat runtime image already exposes port 8080, thus `expose` keyword can be omitted
    # expose:
    #   - "8080"

# Volumes top-level element reference: https://docs.docker.com/compose/compose-file/07-volumes/
volumes:
  mysql-data: {}
